package com.tradet.tradetclienteprueba;
// Generated 08-abr-2020 12:45:27 by Hibernate Tools 4.3.1





/**
 * Categoria generated by hbm2java
 */

public class Categoria  implements java.io.Serializable {


    private Integer categoriaId;
    private String nombre;
     
    public Categoria() {
    }

    public Categoria(Integer categoriaId){
        this.categoriaId = categoriaId;
    }
    public Categoria(String nombre) {
        this.nombre = nombre;
    }

    public Categoria(Integer categoriaId, String nombre) {
        this.categoriaId = categoriaId;
        this.nombre = nombre;
    }
    
   
   


    

    public Integer getCategoriaId() {
        return this.categoriaId;
    }
    
    public void setCategoriaId(Integer categoriaId) {
        this.categoriaId = categoriaId;
    }

    

    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }


  

    @Override
    public String toString() {
        return "Categoria{" + "categoriaId=" + categoriaId + ", nombre=" + nombre + '}';
    }

    


}


