package com.tradet.tradetclienteprueba;
// Generated 08-abr-2020 12:45:27 by Hibernate Tools 4.3.1




/**
 * Producto generated by hbm2java
 */

public class Producto implements java.io.Serializable {

    
    
}
