/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.tradet.programaadministrador;

import javax.swing.JFrame;

/**
 *
 * @author ricar
 */
public class FrmCategorias extends javax.swing.JFrame {
    JFrame parent;
    /**
     * Creates new form FrmCategorias
     */
    public FrmCategorias() {
        initComponents();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblTitulo = new javax.swing.JLabel();
        btnInsertarCategoria = new javax.swing.JButton();
        btnEliminarCategoria = new javax.swing.JButton();

        setMinimumSize(new java.awt.Dimension(454, 236));
        setPreferredSize(new java.awt.Dimension(454, 236));
        setResizable(false);
        getContentPane().setLayout(new java.awt.GridLayout(3, 1, 10, 20));

        lblTitulo.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        lblTitulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTitulo.setText("Categorias");
        getContentPane().add(lblTitulo);

        btnInsertarCategoria.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnInsertarCategoria.setText("Insertar categoría");
        btnInsertarCategoria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInsertarCategoriaActionPerformed(evt);
            }
        });
        getContentPane().add(btnInsertarCategoria);

        btnEliminarCategoria.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnEliminarCategoria.setText("Eliminar categoría");
        btnEliminarCategoria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarCategoriaActionPerformed(evt);
            }
        });
        getContentPane().add(btnEliminarCategoria);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnInsertarCategoriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInsertarCategoriaActionPerformed
        FrmInsertarCategoria frmInsertarCategoria = new FrmInsertarCategoria();
        this.setVisible(false);
        frmInsertarCategoria.setVisible(true);
        
    }//GEN-LAST:event_btnInsertarCategoriaActionPerformed

    private void btnEliminarCategoriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarCategoriaActionPerformed
        FrmEliminarCategoria frmEliminarCategoria = new FrmEliminarCategoria();
        this.setVisible(false);
        frmEliminarCategoria.setVisible(true);
    }//GEN-LAST:event_btnEliminarCategoriaActionPerformed

    /**
     * @param args the command line arguments
     */
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnEliminarCategoria;
    private javax.swing.JButton btnInsertarCategoria;
    private javax.swing.JLabel lblTitulo;
    // End of variables declaration//GEN-END:variables
}
