/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.tradet.programaadministrador;

import com.tradet.excepciones.ExcepcionTradeT;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;


/**
 *
 * @author ricar
 */
public class FrmEliminarCategoria extends javax.swing.JFrame {
    ArrayList<Categoria> listaCategorias;
    /**
     * Creates new form frmEliminarCategoria
     */
    public FrmEliminarCategoria() {
        initComponents();
        setLocationRelativeTo(null);
        ComunicacionServidor comunicacionServidor = new ComunicacionServidor();
        listaCategorias = new ArrayList();
        try {
            listaCategorias = comunicacionServidor.leerCategorias();
            for(Categoria c:listaCategorias){
                cmbCategorias.addItem(c.getNombre());
            }
        } catch (ExcepcionTradeT ex) {
            Logger.getLogger(FrmEliminarCategoria.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblTitulo = new javax.swing.JLabel();
        cmbCategorias = new javax.swing.JComboBox<>();
        jButton1 = new javax.swing.JButton();

        setResizable(false);
        getContentPane().setLayout(new java.awt.GridLayout(3, 1, 0, 20));

        lblTitulo.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        lblTitulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTitulo.setText("Eliminar Categoría");
        getContentPane().add(lblTitulo);

        cmbCategorias.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        getContentPane().add(cmbCategorias);

        jButton1.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jButton1.setText("Eliminar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        
        
        
        ComunicacionServidor comunicacionServidor = new ComunicacionServidor();
        try {
            comunicacionServidor.eliminarCategoria(listaCategorias.get(cmbCategorias.getSelectedIndex()));
            JOptionPane.showMessageDialog(this,
                    "Categoría eliminada correctamente.");
            this.setVisible(false);
        } catch (ExcepcionTradeT ex) {
            JOptionPane.showMessageDialog(this,
                    ex.getCodigoError(),
                    "Error",
                    JOptionPane.ERROR_MESSAGE);
        }
        
        
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> cmbCategorias;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel lblTitulo;
    // End of variables declaration//GEN-END:variables
}
