/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.tradet.programaadministrador;

import com.tradet.excepciones.ExcepcionTradeT;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author ricar
 */
public class FrmEliminarSorteo extends javax.swing.JFrame {
    ArrayList<Sorteo> listaSorteos;
    /**
     * Creates new form FrmEliminarSorteo
     */
    public FrmEliminarSorteo() {
        initComponents();
        setLocationRelativeTo(null);
        ComunicacionServidor comunicacionServidor = new ComunicacionServidor();
        listaSorteos = new ArrayList();
        try {
            listaSorteos = comunicacionServidor.leerSorteos();
            for(Sorteo s:listaSorteos){
                cmbSorteos.addItem(s.getNombre());
            }
        } catch (ExcepcionTradeT ex) {
            Logger.getLogger(FrmEliminarCategoria.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblTitulo = new javax.swing.JLabel();
        cmbSorteos = new javax.swing.JComboBox<>();
        btnElminar = new javax.swing.JButton();

        setMinimumSize(new java.awt.Dimension(803, 199));
        setPreferredSize(new java.awt.Dimension(803, 199));
        setResizable(false);
        getContentPane().setLayout(new java.awt.GridLayout(3, 1, 0, 20));

        lblTitulo.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        lblTitulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTitulo.setText("Eliminar Sorteo");
        getContentPane().add(lblTitulo);

        cmbSorteos.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        getContentPane().add(cmbSorteos);

        btnElminar.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        btnElminar.setText("Eliminar");
        btnElminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnElminarActionPerformed(evt);
            }
        });
        getContentPane().add(btnElminar);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnElminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnElminarActionPerformed
        ComunicacionServidor comunicacionServidor = new ComunicacionServidor();
        try {
            comunicacionServidor.eliminarSorteo(listaSorteos.get(cmbSorteos.getSelectedIndex()));
            JOptionPane.showMessageDialog(this,
                    "Sorteo eliminado correctamente.");
            this.setVisible(false);
        } catch (ExcepcionTradeT ex) {
            JOptionPane.showMessageDialog(this,
                    ex.getCodigoError(),
                    "Error",
                    JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnElminarActionPerformed

    /**
     * @param args the command line arguments
     */
   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnElminar;
    private javax.swing.JComboBox<String> cmbSorteos;
    private javax.swing.JLabel lblTitulo;
    // End of variables declaration//GEN-END:variables
}
