/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.tradet.programaadministrador;

import java.io.BufferedInputStream;
import java.io.IOException;
import java.io.InputStream;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author ricar
 */
public class FrmPantallaPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form FrmPantallaPrincipal
     */
    public FrmPantallaPrincipal() {
        initComponents();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblTitulo = new javax.swing.JLabel();
        btnCategorias = new javax.swing.JButton();
        btnSorteos = new javax.swing.JButton();
        btnHacerCopia = new javax.swing.JButton();
        btnRestaurarCopia = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(520, 240));
        setPreferredSize(new java.awt.Dimension(520, 240));
        setResizable(false);
        getContentPane().setLayout(new java.awt.GridLayout(5, 1, 20, 10));

        lblTitulo.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        lblTitulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTitulo.setText("Administración de Trade-T");
        getContentPane().add(lblTitulo);

        btnCategorias.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnCategorias.setText("Administrar categorias de productos");
        btnCategorias.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCategoriasActionPerformed(evt);
            }
        });
        getContentPane().add(btnCategorias);

        btnSorteos.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnSorteos.setText("Administrar sorteos");
        btnSorteos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSorteosActionPerformed(evt);
            }
        });
        getContentPane().add(btnSorteos);

        btnHacerCopia.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnHacerCopia.setText("Hacer copia de seguridad de la base de datos");
        btnHacerCopia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHacerCopiaActionPerformed(evt);
            }
        });
        getContentPane().add(btnHacerCopia);

        btnRestaurarCopia.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnRestaurarCopia.setText("Restaurar copia de seguridad de la base de datos");
        getContentPane().add(btnRestaurarCopia);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCategoriasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCategoriasActionPerformed
        FrmCategorias frmCategorias = new FrmCategorias();
        frmCategorias.setVisible(true);
    }//GEN-LAST:event_btnCategoriasActionPerformed

    private void btnSorteosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSorteosActionPerformed
        FrmSorteos frmSorteos = new FrmSorteos();
        frmSorteos.setVisible(true);
    }//GEN-LAST:event_btnSorteosActionPerformed

    private void btnHacerCopiaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHacerCopiaActionPerformed
       
    }//GEN-LAST:event_btnHacerCopiaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmPantallaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmPantallaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmPantallaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmPantallaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmPantallaPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCategorias;
    private javax.swing.JButton btnHacerCopia;
    private javax.swing.JButton btnRestaurarCopia;
    private javax.swing.JButton btnSorteos;
    private javax.swing.JLabel lblTitulo;
    // End of variables declaration//GEN-END:variables
}
